#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80
#+    Returns page containing "Hello World!" when queried
#++    at the root with a curl GET request

#Updates package lists for available software packages
apt-get update
#Installs Nginx web server
apt-get install -y nginx

#Creates /etc/nginx/html directory, which will serve as document root directory for Nginx
mkdir /etc/nginx/html
#Creates empty index.html file inside /etc/nginx/html directory
touch /etc/nginx/html/index.html
#Sets content of index.html file to "Hello World!" using the echo command
echo "Hello World!" > /etc/nginx/html/index.html
#Sets Nginx to listen on port 80 and serve files from /etc/nginx/html directory
printf %s "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

#Configure new server block for redirection
echo "server {
    listen 80;
    listen [::]:80;

    root /var/www/html;

    #Add index.php to the list, if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/redirect

#Enable new site configuration
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/


#Test Nginx configuration and reload
sudo nginx -t
sudo service nginx reload
