#!/usr/bin/env bash
#Install HAProxy with the following configurations:
#-Enable management via init script
#-Distribute requests using a round-robin algorithm

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend Randommall.tech
    timeout client  30000
    bind 0:80
    default_backend Randommall.tech_backend

backend Randommall.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 228560-web-01 18.204.15.8:80 check
    server 228560-web-02 54.145.82.52:80 check
EOT

sudo service haproxy restart
