#!/usr/bin/env bash
# This script loops from 1 to 10 with 3 displays
i=0
while ((i < 10)); do
	((i++))

	if [ $i -eq 4 ]; then
		echo "bad luck"

	elif [ $i -eq 8 ]; then
		echo "good luck"

	else
		echo "Best School"
	fi
done
