#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

# Backup the original /etc/hosts file
sudo cp /etc/hosts /etc/hosts.backup

# Configure localhost resolution
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

# Configure facebook.com resolution
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
